Controllers/Encuesta3Controller.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EncuestasV2.Models;
using EncuestasV2.Filters;
using System.Transactions;
using System.Data.Entity.Validation;
using System.Diagnostics;

namespace EncuestasV2.Controllers
{
    public class Encuesta3Controller : Controller
    {

        // GET: Encuesta2
        public ActionResult Index(string user)
        {
            if (user != null)
            {

                ViewBag.user = user.ToString();

                List<encuesta_mostrarPreguntas2CLS> list;
                using (var db = new csstdura_encuestaEntities())
                {
                    //hacemos un select a nuestra tabla con los campos que queremos mostrar
                    list = (from preguntas in db.encuesta_det_encuesta
                            where preguntas.denc_parte == 3
                            select new encuesta_mostrarPreguntas2CLS
                            {
                                denc_id = preguntas.denc_id,
                                denc_descrip = preguntas.denc_descrip,
                                denc_valor_1 = preguntas.denc_valor_1,
                                denc_valor_2 = preguntas.denc_valor_2,
                            }).ToList();

                    string encabezado = db.Database.SqlQuery<string>("select encu_descrip from encuesta_encuesta where encu_id = 1").FirstOrDefault();
                    int id_encabezado = db.Database.SqlQuery<int>("select encu_id from encuesta_encuesta where encu_id = 1").FirstOrDefault();
                    int id_empresa = db.Database.SqlQuery<int>("select usua_empresa from encuesta_usuarios where usua_n_usuario = '" + user + "'").FirstOrDefault();
                    string nombreEmpleado = db.Database.SqlQuery<string>("select usua_nombre from encuesta_usuarios where usua_n_usuario = '" + user + "'").FirstOrDefault();
                    int id_usuario = db.Database.SqlQuery<int>("select usua_id from encuesta_usuarios where usua_n_usuario = '" + user + "'").FirstOrDefault();

                    ViewBag.encabezado = encabezado;
                    ViewBag.id_encabezado = id_encabezado;
                    ViewBag.id_empresa = id_empresa;
                    ViewBag.nombreEmpleado = nombreEmpleado;
                    ViewBag.id_usuario = id_usuario;
                }
                return View(list);
            }
            else
            {
                return RedirectToAction("Index", "Login");
                //return RedirectToAction("Reporting", "ReportManagement", new { area = "Admin" })
            }



        }

        public ActionResult Agregar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Agregar(encuesta_mostrarPreguntas2CLS Oencuesta_mostrarPreguntasCLS)
        {
            String Usuario = Request.Form["user"];
            int res = 0;
            using (var db = new csstdura_encuestaEntities())
            {
                using (var transaction = new TransactionScope())
                {
                    try
                    {
                        for (int x = 1; x < 8; x++)
                        {
                            //var nombreVariable = "radio_"+x;
                            encuesta_resultados resultado = new encuesta_resultados();
                            resultado.resu_emp_id = int.Parse(Request.Form["id_empresa"]);
                            resultado.resu_encu_id = Oencuesta_mostrarPreguntasCLS.encu_id;
                            resultado.resu_denc_id = int.Parse(Request.Form["denc_id_" + x]);//Oencuesta_mostrarPreguntasCLS.denc_id;
                            resultado.resu_usua_id = int.Parse(Request.Form["id_usuario"]);
                            resultado.resu_resultado = Request.Form["Valor_radio_" + x];
                            resultado.resu_fecha = DateTime.Now;
                            db.encuesta_resultados.Add(resultado);
                            res = db.SaveChanges();
                        }

                        transaction.Complete();
                    }
                    catch (DbEntityValidationException dbEx)
                    {

                        foreach (var validationErrors in dbEx.EntityValidationErrors)
                        {
                            foreach (var validationError in validationErrors.ValidationErrors)
                            {
                                Trace.TraceInformation("Property: {0} Error: {1}",
                                    validationError.PropertyName,
                                    validationError.ErrorMessage);
                            }
                        }

                    }
                    if (res == 1)
                    {

                        return Content("<script language='javascript' type='text/javascript'>alert('Registro exitoso!');window.location = '/Encuesta3/Index4?user=" + Usuario + " ';</script>");

                    }
                    else
                    {

                        return Content("<script language='javascript' type='text/javascript'>alert('Ocurrio un error!');window.location = '/Admin/CatalogoEmpresa';</script>");

                    }

                }
            }

        }

        public ActionResult Index4(string user)
        {
            if (user != null)
            {

                ViewBag.user = user.ToString();

                List<encuesta_mostrarPreguntas2CLS> list;
                using (var db = new csstdura_encuestaEntities())
                {
                    //hacemos un select a nuestra tabla con los campos que queremos mostrar
                    list = (from preguntas in db.encuesta_det_encuesta
                            where preguntas.denc_parte == 4
                            select new encuesta_mostrarPreguntas2CLS
                            {
                                denc_id = preguntas.denc_id,
                                denc_descrip = preguntas.denc_descrip,
                                denc_valor_1 = preguntas.denc_valor_1,
                                denc_valor_2 = preguntas.denc_valor_2,
                            }).ToList();

                    string encabezado = db.Database.SqlQuery<string>("select encu_descrip from encuesta_encuesta where encu_id = 1").FirstOrDefault();
                    int id_encabezado = db.Database.SqlQuery<int>("select encu_id from encuesta_encuesta where encu_id = 1").FirstOrDefault();
                    int id_empresa = db.Database.SqlQuery<int>("select usua_empresa from encuesta_usuarios where usua_n_usuario = '" + user + "'").FirstOrDefault();
                    string nombreEmpleado = db.Database.SqlQuery<string>("select usua_nombre from encuesta_usuarios where usua_n_usuario = '" + user + "'").FirstOrDefault();
                    int id_usuario = db.Database.SqlQuery<int>("select usua_id from encuesta_usuarios where usua_n_usuario = '" + user + "'").FirstOrDefault();

                    ViewBag.encabezado = encabezado;
                    ViewBag.id_encabezado = id_encabezado;
                    ViewBag.id_empresa = id_empresa;
                    ViewBag.nombreEmpleado = nombreEmpleado;
                    ViewBag.id_usuario = id_usuario;
                }
                return View(list);
            }
            else
            {
                return RedirectToAction("Index", "Login");
                //return RedirectToAction("Reporting", "ReportManagement", new { area = "Admin" })
            }



        }

        public ActionResult Agregar4()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Agregar4(encuesta_mostrarPreguntas2CLS Oencuesta_mostrarPreguntasCLS)
        {
            String Usuario = Request.Form["user"];
            int res = 0;
            using (var db = new csstdura_encuestaEntities())
            {
                using (var transaction = new TransactionScope())
                {
                    try
                    {
                        for (int x = 1; x < 6; x++)
                        {
                            //var nombreVariable = "radio_"+x;
                            encuesta_resultados resultado = new encuesta_resultados();
                            resultado.resu_emp_id = int.Parse(Request.Form["id_empresa"]);
                            resultado.resu_encu_id = Oencuesta_mostrarPreguntasCLS.encu_id;
                            resultado.resu_denc_id = int.Parse(Request.Form["denc_id_" + x]);//Oencuesta_mostrarPreguntasCLS.denc_id;
                            resultado.resu_usua_id = int.Parse(Request.Form["id_usuario"]);
                            resultado.resu_resultado = Request.Form["Valor_radio_" + x];
                            resultado.resu_fecha = DateTime.Now;
                            db.encuesta_resultados.Add(resultado);
                            res = db.SaveChanges();
                        }

                        transaction.Complete();
                    }
                    catch (DbEntityValidationException dbEx)
                    {

                        foreach (var validationErrors in dbEx.EntityValidationErrors)
                        {
                            foreach (var validationError in validationErrors.ValidationErrors)
                            {
                                Trace.TraceInformation("Property: {0} Error: {1}",
                                    validationError.PropertyName,
                                    validationError.ErrorMessage);
                            }
                        }

                    }
                    if (res == 1)
                    {

Views/Encuesta3/Index.cshtml
@{
    ViewBag.Title = "Index";
    int x = 1;
}

<h2>Bienvenido: @ViewBag.nombreEmpleado</h2>
@*<h2>Usuario-@ViewBag.Session</h2>*@

@using (Html.BeginForm("Agregar", "Encuesta3", FormMethod.Post))
{
    <h4> @ViewBag.encabezado</h4>
    @Html.TextBox("user", ViewBag.user as string, new { type = "hidden" })
    <input type="hidden" id="encu_id" name="encu_id" value=@ViewBag.id_encabezado />
    <input type="hidden" id="id_usuario" name="id_usuario" value=@ViewBag.id_usuario />
    <input type="hidden" id="id_empresa" name="id_empresa" value=@ViewBag.id_empresa />

    <h5><strong>III.- Esfuerzo por evitar circunstancias parecidas o asociadas al acontecimiento (durante el último mes):</strong></h5>

    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>PREGUNTA</th>
                <th>SI</th>
                <th>NO</th>
            </tr>
        </thead>
        <!-- Recorro el modelo para imprimir datos -->
        @foreach (var elemento in Model)
        {

            <tr>

                <td>
                    <input type="hidden" name="denc_id_@x" value="@elemento.denc_id" />@elemento.denc_id
                    <input type="hidden" name="Valor_radio_@x" id="Valor_radio_@x" />
                </td>
                <td>@elemento.denc_descrip</td>
                <td><input onclick="ValRadio1(@x);" type="radio" id="radio1_@x" name="radio_@x" value="@elemento.denc_valor_1" required /></td>
                <td><input onclick="ValRadio2(@x);" type="radio" id="radio2_@x" name="radio_@x" value="@elemento.denc_valor_2" required /></td>

            </tr>
            x = x + 1;
        }
        <tr>
            <td><input type="submit" value="Guardar" class="btn btn-primary" /></td>
        </tr>
    </table>

}

<script>
    function ValRadio1(valor_x) {
        document.getElementById("Valor_radio_" + valor_x).value = document.getElementById("radio1_" + valor_x).value;
    }

    function ValRadio2(valor_x) {
        document.getElementById("Valor_radio_" + valor_x).value = document.getElementById("radio2_" + valor_x).value;
    }
</script>

Views/Encuesta3/Index10.cshtml
@{
    ViewBag.Title = "Index";
    int x = 1;
}

<h2>Bienvenido: @ViewBag.nombreEmpleado</h2>
@*<h2>Usuario-@ViewBag.Session</h2>*@

@using (Html.BeginForm("Agregar10", "Encuesta3", FormMethod.Post))
{
    <h4> @ViewBag.encabezado</h4>
    @Html.TextBox("user", ViewBag.user as string, new { type = "hidden" })
    <input type="hidden" id="encu_id" name="encu_id" value=@ViewBag.id_encabezado />
    <input type="hidden" id="id_usuario" name="id_usuario" value=@ViewBag.id_usuario />
    <input type="hidden" id="id_empresa" name="id_empresa" value=@ViewBag.id_empresa />

    <h5>Las preguntas siguientes se refieren a las relaciones con sus compañeros de trabajo y su jefe.</h5>


    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>PREGUNTA</th>
                <th>SIEMPRE</th>
                <th>CASI SIEMPRE</th>
                <th>ALGUNAS VECES</th>
                <th>CASI NUNCA</th>
                <th>NUNCA</th>
            </tr>
        </thead>
        <!-- Recorro el modelo para imprimir datos -->
        @foreach (var elemento in Model)
        {

            <tr>

                <td>
                    <input type="hidden" name="denc_id_@x" value="@elemento.denc_id" />@elemento.denc_id
                    <input type="hidden" name="Valor_radio_@x" id="Valor_radio_@x" />
                </td>
                <td>@elemento.denc_descrip</td>
                <td><input onclick="ValRadio1(@x);" type="radio" id="radio1_@x" name="radio_@x" value="@elemento.denc_valor_1" required /></td>
                <td><input onclick="ValRadio2(@x);" type="radio" id="radio2_@x" name="radio_@x" value="@elemento.denc_valor_2" required /></td>
                <td><input onclick="ValRadio3(@x);" type="radio" id="radio3_@x" name="radio_@x" value="@elemento.denc_valor_3" required /></td>
                <td><input onclick="ValRadio4(@x);" type="radio" id="radio4_@x" name="radio_@x" value="@elemento.denc_valor_4" required /></td>
                <td><input onclick="ValRadio5(@x);" type="radio" id="radio5_@x" name="radio_@x" value="@elemento.denc_valor_5" required /></td>

            </tr>
            x = x + 1;
        }
        <tr>
            <td><input type="submit" value="Guardar" class="btn btn-primary" /></td>
        </tr>
    </table>

}

<script>
    function ValRadio1(valor_x) {
        document.getElementById("Valor_radio_" + valor_x).value = document.getElementById("radio1_" + valor_x).value;
    }
    function ValRadio2(valor_x) {
        document.getElementById("Valor_radio_" + valor_x).value = document.getElementById("radio2_" + valor_x).value;
    }
    function ValRadio3(valor_x) {
        document.getElementById("Valor_radio_" + valor_x).value = document.getElementById("radio3_" + valor_x).value;
    }
    function ValRadio4(valor_x) {
        document.getElementById("Valor_radio_" + valor_x).value = document.getElementById("radio4_" + valor_x).value;
    }
    function ValRadio5(valor_x) {
        document.getElementById("Valor_radio_" + valor_x).value = document.getElementById("radio5_" + valor_x).value;
    }

</script>

Views/Encuesta3/Index14.cshtml
@{
    ViewBag.Title = "Index";
    int x = 1;
}

<h2>Bienvenido: @ViewBag.nombreEmpleado</h2>
@*<h2>Usuario-@ViewBag.Session</h2>*@

@using (Html.BeginForm("Agregar14", "Encuesta3", FormMethod.Post))
{
    <h4> @ViewBag.encabezado</h4>
    @Html.TextBox("user", ViewBag.user as string, new { type = "hidden" })
    <input type="hidden" id="encu_id" name="encu_id" value=@ViewBag.id_encabezado />
    <input type="hidden" id="id_usuario" name="id_usuario" value=@ViewBag.id_usuario />
    <input type="hidden" id="id_empresa" name="id_empresa" value=@ViewBag.id_empresa />

    <h5>Para responder a las preguntas siguientes piense en la cantidad y ritmo de trabajo que tiene.</h5>


    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>PREGUNTA</th>
                <th>SIEMPRE</th>
                <th>CASI SIEMPRE</th>
                <th>ALGUNAS VECES</th>
                <th>CASI NUNCA</th>
                <th>NUNCA</th>
            </tr>
        </thead>
        <!-- Recorro el modelo para imprimir datos -->
        @foreach (var elemento in Model)
        {

            <tr>

                <td>
                    <input type="hidden" name="denc_id_@x" value="@elemento.denc_id" />@elemento.denc_id
                    <input type="hidden" name="Valor_radio_@x" id="Valor_radio_@x" />
                </td>
                <td>@elemento.denc_descrip</td>
                <td><input onclick="ValRadio1(@x);" type="radio" id="radio1_@x" name="radio_@x" value="@elemento.denc_valor_1" required /></td>
                <td><input onclick="ValRadio2(@x);" type="radio" id="radio2_@x" name="radio_@x" value="@elemento.denc_valor_2" required /></td>
                <td><input onclick="ValRadio3(@x);" type="radio" id="radio3_@x" name="radio_@x" value="@elemento.denc_valor_3" required /></td>
                <td><input onclick="ValRadio4(@x);" type="radio" id="radio4_@x" name="radio_@x" value="@elemento.denc_valor_4" required /></td>
                <td><input onclick="ValRadio5(@x);" type="radio" id="radio5_@x" name="radio_@x" value="@elemento.denc_valor_5" required /></td>

            </tr>
            x = x + 1;
        }
        <tr>
            <td><input type="submit" value="Guardar" class="btn btn-primary" /></td>
        </tr>
    </table>

}

<script>
    function ValRadio1(valor_x) {
        document.getElementById("Valor_radio_" + valor_x).value = document.getElementById("radio1_" + valor_x).value;
    }
    function ValRadio2(valor_x) {
        document.getElementById("Valor_radio_" + valor_x).value = document.getElementById("radio2_" + valor_x).value;
    }
    function ValRadio3(valor_x) {
        document.getElementById("Valor_radio_" + valor_x).value = document.getElementById("radio3_" + valor_x).value;
    }
    function ValRadio4(valor_x) {
        document.getElementById("Valor_radio_" + valor_x).value = document.getElementById("radio4_" + valor_x).value;
    }
    function ValRadio5(valor_x) {
        document.getElementById("Valor_radio_" + valor_x).value = document.getElementById("radio5_" + valor_x).value;
    }

</script>

Views/Encuesta3/Index17.cshtml
@{
    ViewBag.Title = "Index";
    int x = 1;
}

<h2>Bienvenido: @ViewBag.nombreEmpleado</h2>
@*<h2>Usuario-@ViewBag.Session</h2>*@

@using (Html.BeginForm("Agregar17", "Encuesta3", FormMethod.Post))
{
    <h4> @ViewBag.encabezado</h4>
    @Html.TextBox("user", ViewBag.user as string, new { type = "hidden" })
    <input type="hidden" id="encu_id" name="encu_id" value=@ViewBag.id_encabezado />
    <input type="hidden" id="id_usuario" name="id_usuario" value=@ViewBag.id_usuario />
    <input type="hidden" id="id_empresa" name="id_empresa" value=@ViewBag.id_empresa />

    <h5>Las preguntas siguientes están relacionadas con su jornada de trabajo.</h5>


    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>PREGUNTA</th>
                <th>SIEMPRE</th>
                <th>CASI SIEMPRE</th>
                <th>ALGUNAS VECES</th>
                <th>CASI NUNCA</th>
                <th>NUNCA</th>
            </tr>
        </thead>
        <!-- Recorro el modelo para imprimir datos -->
        @foreach (var elemento in Model)
        {

            <tr>

                <td>
                    <input type="hidden" name="denc_id_@x" value="@elemento.denc_id" />@elemento.denc_id
                    <input type="hidden" name="Valor_radio_@x" id="Valor_radio_@x" />
                </td>
                <td>@elemento.denc_descrip</td>
                <td><input onclick="ValRadio1(@x);" type="radio" id="radio1_@x" name="radio_@x" value="@elemento.denc_valor_1" required /></td>
                <td><input onclick="ValRadio2(@x);" type="radio" id="radio2_@x" name="radio_@x" value="@elemento.denc_valor_2" required /></td>
                <td><input onclick="ValRadio3(@x);" type="radio" id="radio3_@x" name="radio_@x" value="@elemento.denc_valor_3" required /></td>
                <td><input onclick="ValRadio4(@x);" type="radio" id="radio4_@x" name="radio_@x" value="@elemento.denc_valor_4" required /></td>
                <td><input onclick="ValRadio5(@x);" type="radio" id="radio5_@x" name="radio_@x" value="@elemento.denc_valor_5" required /></td>

            </tr>
            x = x + 1;
        }
        <tr>
            <td><input type="submit" value="Guardar" class="btn btn-primary" /></td>
        </tr>
    </table>

}

<script>
    function ValRadio1(valor_x) {
        document.getElementById("Valor_radio_" + valor_x).value = document.getElementById("radio1_" + valor_x).value;
    }
    function ValRadio2(valor_x) {
        document.getElementById("Valor_radio_" + valor_x).value = document.getElementById("radio2_" + valor_x).value;
    }
    function ValRadio3(valor_x) {
        document.getElementById("Valor_radio_" + valor_x).value = document.getElementById("radio3_" + valor_x).value;
    }
    function ValRadio4(valor_x) {
        document.getElementById("Valor_radio_" + valor_x).value = document.getElementById("radio4_" + valor_x).value;
    }
    function ValRadio5(valor_x) {
        document.getElementById("Valor_radio_" + valor_x).value = document.getElementById("radio5_" + valor_x).value;
    }

</script>

Views/Encuesta3/Index18.cshtml
@{
    ViewBag.Title = "Index";
    int x = 1;
}

<h2>Bienvenido: @ViewBag.nombreEmpleado</h2>
@*<h2>Usuario-@ViewBag.Session</h2>*@

@using (Html.BeginForm("Agregar18", "Encuesta3", FormMethod.Post))
{
    <h4> @ViewBag.encabezado</h4>
    @Html.TextBox("user", ViewBag.user as string, new { type = "hidden" })
    <input type="hidden" id="encu_id" name="encu_id" value=@ViewBag.id_encabezado />
    <input type="hidden" id="id_usuario" name="id_usuario" value=@ViewBag.id_usuario />
    <input type="hidden" id="id_empresa" name="id_empresa" value=@ViewBag.id_empresa />

    <h5>Las preguntas siguientes están relacionadas con las decisiones que puede tomar en su trabajo.</h5>


    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>PREGUNTA</th>
                <th>SIEMPRE</th>
                <th>CASI SIEMPRE</th>
                <th>ALGUNAS VECES</th>
                <th>CASI NUNCA</th>
                <th>NUNCA</th>
            </tr>
        </thead>
        <!-- Recorro el modelo para imprimir datos -->
        @foreach (var elemento in Model)
        {

            <tr>

                <td>
                    <input type="hidden" name="denc_id_@x" value="@elemento.denc_id" />@elemento.denc_id
                    <input type="hidden" name="Valor_radio_@x" id="Valor_radio_@x" />
                </td>
                <td>@elemento.denc_descrip</td>
                <td><input onclick="ValRadio1(@x);" type="radio" id="radio1_@x" name="radio_@x" value="@elemento.denc_valor_1" required /></td>
                <td><input onclick="ValRadio2(@x);" type="radio" id="radio2_@x" name="radio_@x" value="@elemento.denc_valor_2" required /></td>
                <td><input onclick="ValRadio3(@x);" type="radio" id="radio3_@x" name="radio_@x" value="@elemento.denc_valor_3" required /></td>
                <td><input onclick="ValRadio4(@x);" type="radio" id="radio4_@x" name="radio_@x" value="@elemento.denc_valor_4" required /></td>
                <td><input onclick="ValRadio5(@x);" type="radio" id="radio5_@x" name="radio_@x" value="@elemento.denc_valor_5" required /></td>

            </tr>
            x = x + 1;
        }
        <tr>
            <td><input type="submit" value="Guardar" class="btn btn-primary" /></td>
        </tr>
    </table>

}

<script>
    function ValRadio1(valor_x) {
        document.getElementById("Valor_radio_" + valor_x).value = document.getElementById("radio1_" + valor_x).value;
    }
    function ValRadio2(valor_x) {
        document.getElementById("Valor_radio_" + valor_x).value = document.getElementById("radio2_" + valor_x).value;
    }
    function ValRadio3(valor_x) {
        document.getElementById("Valor_radio_" + valor_x).value = document.getElementById("radio3_" + valor_x).value;
    }
    function ValRadio4(valor_x) {
        document.getElementById("Valor_radio_" + valor_x).value = document.getElementById("radio4_" + valor_x).value;
    }
    function ValRadio5(valor_x) {
        document.getElementById("Valor_radio_" + valor_x).value = document.getElementById("radio5_" + valor_x).value;
    }

</script>

Views/Encuesta3/Index19.cshtml
@{
    ViewBag.Title = "Index";
    int x = 1;
}

<h2>Bienvenido: @ViewBag.nombreEmpleado</h2>
@*<h2>Usuario-@ViewBag.Session</h2>*@

@using (Html.BeginForm("Agregar19", "Encuesta3", FormMethod.Post))
{
    <h4> @ViewBag.encabezado</h4>
    @Html.TextBox("user", ViewBag.user as string, new { type = "hidden" })
    <input type="hidden" id="encu_id" name="encu_id" value=@ViewBag.id_encabezado />
    <input type="hidden" id="id_usuario" name="id_usuario" value=@ViewBag.id_usuario />
    <input type="hidden" id="id_empresa" name="id_empresa" value=@ViewBag.id_empresa />

    <h5>Las preguntas siguientes están relacionadas con cualquier tipo de cambio que ocurra en su trabajo (considere los últimos cambios realizados).</h5>


    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>PREGUNTA</th>
                <th>SIEMPRE</th>
                <th>CASI SIEMPRE</th>
                <th>ALGUNAS VECES</th>
                <th>CASI NUNCA</th>
                <th>NUNCA</th>
            </tr>
        </thead>
        <!-- Recorro el modelo para imprimir datos -->
        @foreach (var elemento in Model)
        {

            <tr>

                <td>
                    <input type="hidden" name="denc_id_@x" value="@elemento.denc_id" />@elemento.denc_id
                    <input type="hidden" name="Valor_radio_@x" id="Valor_radio_@x" />
                </td>
                <td>@elemento.denc_descrip</td>
                <td><input onclick="ValRadio1(@x);" type="radio" id="radio1_@x" name="radio_@x" value="@elemento.denc_valor_1" required /></td>
                <td><input onclick="ValRadio2(@x);" type="radio" id="radio2_@x" name="radio_@x" value="@elemento.denc_valor_2" required /></td>
                <td><input onclick="ValRadio3(@x);" type="radio" id="radio3_@x" name="radio_@x" value="@elemento.denc_valor_3" required /></td>
                <td><input onclick="ValRadio4(@x);" type="radio" id="radio4_@x" name="radio_@x" value="@elemento.denc_valor_4" required /></td>
                <td><input onclick="ValRadio5(@x);" type="radio" id="radio5_@x" name="radio_@x" value="@elemento.denc_valor_5" required /></td>

            </tr>
            x = x + 1;
        }
        <tr>
            <td><input type="submit" value="Guardar" class="btn btn-primary" /></td>
        </tr>
    </table>

}

<script>
    function ValRadio1(valor_x) {
        document.getElementById("Valor_radio_" + valor_x).value = document.getElementById("radio1_" + valor_x).value;
    }
    function ValRadio2(valor_x) {
        document.getElementById("Valor_radio_" + valor_x).value = document.getElementById("radio2_" + valor_x).value;
    }
    function ValRadio3(valor_x) {
        document.getElementById("Valor_radio_" + valor_x).value = document.getElementById("radio3_" + valor_x).value;
    }
    function ValRadio4(valor_x) {
        document.getElementById("Valor_radio_" + valor_x).value = document.getElementById("radio4_" + valor_x).value;
    }
    function ValRadio5(valor_x) {
        document.getElementById("Valor_radio_" + valor_x).value = document.getElementById("radio5_" + valor_x).value;
    }

</script>

Views/Encuesta3/Index27.cshtml
@{
    ViewBag.Title = "Index";
}
<br /><br />
      <div align="center">
          <h3>Gracias @ViewBag.nombreEmpleado por contestar nuestro cuestionario</h3>

          <br /><br />
          <h4>Que tengas buen día.</h4>
          <br /><br />

          @using (Html.BeginForm("Agregar27", "Encuesta3", FormMethod.Post, new { id = "Form" }))
          {
              @Html.TextBox("user", ViewBag.user as string, new { type = "hidden" })
              <input type="hidden" id="id_usuario" name="id_usuario" value=@ViewBag.id_usuario />

              <input type="submit" value="Terminar" class="btn btn-primary" />
              <br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
          }
      </div>