Controllers/EncuestaController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EncuestasV2.Models;
using EncuestasV2.Filters;
using System.Transactions;
using System.Data.Entity.Validation;
using System.Diagnostics;

namespace EncuestasV2.Controllers
{

    [Acceder]
    public class EncuestaController : Controller
    {
        // GET: Encuesta
        public ActionResult Index(string user)
        {
            if (user != null)
            {
                ViewBag.user = user.ToString();

                List<encuesta_mostrarPreguntasCLS> list;
                using (var db = new csstdura_encuestaEntities())
                {
                    //hacemos un select a nuestra tabla con los campos que queremos mostrar
                    list = (from preguntas in db.encuesta_det_encuesta
                            where preguntas.denc_parte == 1
                            select new encuesta_mostrarPreguntasCLS
                            {
                                denc_id = preguntas.denc_id,
                                denc_descrip = preguntas.denc_descrip,
                                denc_valor_1 = preguntas.denc_valor_1,
                                denc_valor_2 = preguntas.denc_valor_2,
                            }).ToList();

                    string encabezado = db.Database.SqlQuery<string>("select encu_descrip from encuesta_encuesta where encu_id = 1").FirstOrDefault();
                    int id_encabezado = db.Database.SqlQuery<int>("select encu_id from encuesta_encuesta where encu_id = 1").FirstOrDefault();
                    int id_empresa = db.Database.SqlQuery<int>("select usua_empresa from encuesta_usuarios where usua_n_usuario = '"+ user + "'").FirstOrDefault();
                    string nombreEmpleado = db.Database.SqlQuery<string>("select usua_nombre from encuesta_usuarios where usua_n_usuario = '" + user + "'").FirstOrDefault();
                    int id_usuario = db.Database.SqlQuery<int>("select usua_id from encuesta_usuarios where usua_n_usuario = '" + user + "'").FirstOrDefault();

                    ViewBag.encabezado = encabezado;
                    ViewBag.id_encabezado = id_encabezado;
                    ViewBag.id_empresa = id_empresa;
                    ViewBag.nombreEmpleado = nombreEmpleado;
                    ViewBag.id_usuario = id_usuario;
                }
                return View(list);
            }
            else {
                return RedirectToAction("Index", "Login");
                //return RedirectToAction("Reporting", "ReportManagement", new { area = "Admin" })
            }
            
       

        }



        public ActionResult Agregar()
        {
            return View();
        }
 
        [HttpPost]
        public ActionResult Agregar(encuesta_mostrarPreguntasCLS Oencuesta_mostrarPreguntasCLS)
        {
            String Usuario = Request.Form["user"];
            int res = 0;
            int bandera = 0;
            using (var db = new csstdura_encuestaEntities())
            {
                using (var transaction = new TransactionScope())
                {
                    int id_empresa = db.Database.SqlQuery<int>("select usua_empresa from encuesta_usuarios where usua_n_usuario = '" + Usuario + "'").FirstOrDefault();
                    String num_empleados = db.Database.SqlQuery<String>("select emp_no_trabajadores from encuesta_empresa where emp_id = '" + id_empresa + "'").FirstOrDefault();

                    try
                    {
                        for (int x = 1; x<7; x++)
                        {
                            //var nombreVariable = "radio_"+x;
                            encuesta_resultados resultado = new encuesta_resultados();
                            resultado.resu_emp_id = int.Parse(Request.Form["id_empresa"]);
                            resultado.resu_encu_id = Oencuesta_mostrarPreguntasCLS.encu_id;
                            resultado.resu_denc_id = int.Parse(Request.Form["denc_id_" + x]);//Oencuesta_mostrarPreguntasCLS.denc_id;
                            resultado.resu_usua_id = int.Parse(Request.Form["id_usuario"]);
                            resultado.resu_resultado = Request.Form["Valor_radio_"+x];
                            if (Request.Form["Valor_radio_" + x].Equals("SI"))
                            {
                                bandera = 1;
                            }
                            resultado.resu_fecha = DateTime.Now;
                            db.encuesta_resultados.Add(resultado);
                            res = db.SaveChanges();
                        }
                        
                        transaction.Complete();
                    }
                    catch (DbEntityValidationException dbEx)
                    {

                        foreach (var validationErrors in dbEx.EntityValidationErrors)
                        {
                            foreach (var validationError in validationErrors.ValidationErrors)
                            {
                                Trace.TraceInformation("Property: {0} Error: {1}",
                                    validationError.PropertyName,
                                    validationError.ErrorMessage);
                            }
                        }

                    }
                    if (res == 1)
                    {
                        if (bandera == 1)
                        {
                            return Content("<script language='javascript' type='text/javascript'>alert('Registro exitoso!');window.location = '/Encuesta2/Index?user=" + Usuario + " ';</script>");
                        }
                        else
                        {

                            if (int.Parse(num_empleados) < 51)
                            {
                                return Content("<script language='javascript' type='text/javascript'>alert('Registro exitoso!');window.location = '/Encuesta3/Index5?user=" + Usuario + " ';</script>");
                            }
                            {
                                return Content("<script language='javascript' type='text/javascript'>alert('Registro exitoso!');window.location = '/Encuesta3/Index13?user=" + Usuario + " ';</script>");
                            }
                        }

                    }
                    else
                    {

                        return Content("<script language='javascript' type='text/javascript'>alert('Ocurrio un error!');window.location = '/Admin/CatalogoEmpresa';</script>");

                    }

                }
            }

        }

    }

    
}

Views/Encuesta/Index.cshtml
@{
    ViewBag.Title = "Index";
    int x = 1;
}

<h2>Bienvenido: @ViewBag.nombreEmpleado</h2>
@*<h2>Usuario-@ViewBag.Session</h2>*@

@using (Html.BeginForm("Agregar", "Encuesta", FormMethod.Post))
{
    <h4> @ViewBag.encabezado</h4>
    @Html.TextBox("user", ViewBag.user as string, new { type = "hidden" })
    <input type="hidden" id="encu_id" name="encu_id" value=@ViewBag.id_encabezado />
    <input type="hidden" id="id_usuario" name="id_usuario" value=@ViewBag.id_usuario />
    <input type="hidden" id="id_empresa" name="id_empresa" value=@ViewBag.id_empresa />

    <h5><strong>I.- Acontecimiento traumático severo</strong></h5>

    <h5>¿Ha presenciado o sufrido alguna vez, durante o con motivo del trabajo un acontecimiento como los siguientes:</h5>


    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>PREGUNTA</th>
                <th>SI</th>
                <th>NO</th>
            </tr>
        </thead>
        <!-- Recorro el modelo para imprimir datos -->
        @foreach (var elemento in Model)
        {

            <tr>

                <td>
                    <input type="hidden" name="denc_id_@x" value="@elemento.denc_id" />@elemento.denc_id
                    <input type="hidden" name="Valor_radio_@x" id="Valor_radio_@x" />
                </td>
                <td>@elemento.denc_descrip</td>
                <td><input onclick="ValRadio1(@x);" type="radio" id="radio1_@x" name="radio_@x" value="@elemento.denc_valor_1" required /></td>
                <td><input onclick="ValRadio2(@x);" type="radio" id="radio2_@x" name="radio_@x" value="@elemento.denc_valor_2" required /></td>

            </tr>
            x = x + 1;
        }
        <tr>
            <td><input type="submit" value="Guardar" class="btn btn-primary" /></td>
        </tr>
    </table>

}

<script>
    function ValRadio1(valor_x) {
        document.getElementById("Valor_radio_" + valor_x).value = document.getElementById("radio1_" + valor_x).value;
    }

    function ValRadio2(valor_x) {
        document.getElementById("Valor_radio_" + valor_x).value = document.getElementById("radio2_" + valor_x).value;
    }
</script>